apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qwerty
  annotations:
    github.com/project-slug: backstage-janus-test/qwerty
    backstage.io/techdocs-ref: dir:.
  links:
    - title: Git URL
      url: https://github.com?owner=backstage-janus-test&repo=qwerty
spec:
  type: service
  lifecycle: production
  owner: default/owner
